# Auto-generated using compose2nix v0.3.2-pre.
{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."immich_machine_learning" = {
    image = "ghcr.io/immich-app/immich-machine-learning:release-cuda";
    volumes = [
      "immich_remote_ml_model-cache:/cache:rw"
    ];
    ports = [
      "3003:3003/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--device=nvidia.com/gpu=all"
      "--network-alias=immich-machine-learning"
      "--network=immich_remote_ml_default"
    ];
  };
  systemd.services."podman-immich_machine_learning" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-immich_remote_ml_default.service"
      "podman-volume-immich_remote_ml_model-cache.service"
    ];
    requires = [
      "podman-network-immich_remote_ml_default.service"
      "podman-volume-immich_remote_ml_model-cache.service"
    ];
    partOf = [
      "podman-compose-immich_remote_ml-root.target"
    ];
    wantedBy = [
      "podman-compose-immich_remote_ml-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-immich_remote_ml_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f immich_remote_ml_default";
    };
    script = ''
      podman network inspect immich_remote_ml_default || podman network create immich_remote_ml_default
    '';
    partOf = [ "podman-compose-immich_remote_ml-root.target" ];
    wantedBy = [ "podman-compose-immich_remote_ml-root.target" ];
  };

  # Volumes
  systemd.services."podman-volume-immich_remote_ml_model-cache" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect immich_remote_ml_model-cache || podman volume create immich_remote_ml_model-cache
    '';
    partOf = [ "podman-compose-immich_remote_ml-root.target" ];
    wantedBy = [ "podman-compose-immich_remote_ml-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-immich_remote_ml-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
